# RoboPlan configuration file for the CLR robot model.
# TODO: Still not tuned up

joint_limits:
  ewellix_lift_lower_to_higher:
    max_acceleration: [1.0]
    max_jerk: [2.0]
  vention_rail_base_to_carriage:
    max_acceleration: [1.0]
    max_jerk: [2.0]
  shoulder_pan_joint:
    max_acceleration: [1.0]
    max_jerk: [10.0]
  shoulder_lift_joint:
    max_acceleration: [1.0]
    max_jerk: [10.0]
  elbow_joint:
    max_acceleration: [1.0]
    max_jerk: [10.0]
  wrist_1_joint:
    max_acceleration: [1.0]
    max_jerk: [10.0]
  wrist_2_joint:
    max_acceleration: [1.0]
    max_jerk: [10.0]
  wrist_3_joint:
    max_acceleration: [1.0]
    max_jerk: [10.0]
