build:
  symlink-install: true
  mixin:
    - rel-with-deb-info
    - build-testing-on
    - ccache
    - compile-commands
  packages-ignore:
    - btcpp_ros2_samples
test:
  event-handlers:
    - console_direct+
  packages-ignore:
    - btcpp_ros2_samples
